apiVersion: apps/v1
kind: Deployment
metadata:
  name: caesar-cipher
  namespace: cipher-ns
  labels:
    app: caesar-cipher
    version: 0.0.2-run2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caesar-cipher
      version: 0.0.2-run2
  template:
    metadata:
      labels:
        app: caesar-cipher
        version: 0.0.2-run2
    spec:
      containers:
      - name: caesar-cipher
        image: cicerow/caesar-cipher:0.0.2-run2
        ports:
        - containerPort: 5000
      imagePullSecrets:
      # Create this secret mannually in your cluster before apply
      - name: my-docker-credentials
