apiVersion: v1
kind: Pod
metadata:
  name: caesar-cipher-test-curl-pod2
  namespace: cipher-ns
  labels:
    app: caesar-cipher-test-curl-pod2
    version: 0.0.2-run2
spec:
  containers:
  - name: caesar-cipher-test-curl-pod2
    image: curlimages/curl
    command: ["/bin/sh"]
    args:
    - -c
    - |
      echo 5 > /tmp/time_interval.cfg
      while true; do
        TIME_INTERVAL=$(cat /tmp/time_interval.cfg)
        date +'%Y/%m/%d %H:%M:%S'

        echo ---- Invalid URL path ----
        curl -sSi -X POST http://caesar-cipher.cipher-ns.svc.cluster.local:5001/invalid | grep -E '(HTTP/1.1 404|404 Not Found)'
        echo

        echo ---- Invalid HTTP method ----
        curl -sSi -X PuT http://caesar-cipher.cipher-ns.svc.cluster.local:5001/ | grep -E '(HTTP/1.1 400|Invalid Method)'
        echo

        sleep $TIME_INTERVAL
      done
