apiVersion: v1
kind: Service
metadata:
  name: caesar-cipher
  labels:
    app: caesar-cipher
    version: 0.0.2-run2
spec:
  type: ClusterIP
  externalIPs:
  - 172.22.185.230 # my local wsl
  - 172.31.62.143  # my AWS instance
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5000
  selector:
    app: caesar-cipher
